Kernel360/KDEV4-HouseHub-BE

.github/workflows/deploy.yml, src/main/java/com/househub/backend/domain/agent/entity/Agent.java, src/main/java/com/househub/backend/domain/agent/entity/RealEstate.java, src/main/java/com/househub/backend/domain/agent/repository/AgentRepository.java, src/main/java/com/househub/backend/domain/auth/controller/AuthController.java, src/main/java/com/househub/backend/domain/auth/dto/SignUpRequestDto.java, src/main/java/com/househub/backend/domain/auth/exception/EmailVerifiedException.java, src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java, src/test/java/com/househub/backend/domain/auth/controller/AuthControllerTest.java, src/test/java/com/househub/backend/domain/auth/service/AuthServiceImplTest.java
회원가입 방식 간소화에 따른 코드 및 단위 테스트 코드 변경
- SignUpRequestDto 유효성 검사 규칙 변경 및 emailVerified 필드 추가
- 부동산 정보는 선택 값으로 지정
- 회원가입 중 이메일 중복여부 체크 로직 및 예외 처리 추가 
- 이메일 중복여부 체크에 따른 서비스 단위 테스트 추가 
- 공인중개사 자격증 번호 선택값에 따른 if 조건문 추가
- 부동산 정보 선택값에 따른 사업자등록번호 if 조건문 추가
- 관리자 승인 없이 바로 가입 처리
- #26 
- #30
=> 회원가입 방식 간소화에 따른 코드 및 단위 테스트 코드 변경, 워크 플로우 빌드 단계 스크립트 수정

src/test/java/com/househub/backend/HouseHubBackendApplicationTests.java
- CI/CD 과정에서 빌드 실패하는 원인을 찾아냄
- HouseHubBackendApplicationTest에서 contextload가 실패
- 테스트 클래스 위에 클래스를 명시
- #22
=> youngseok, bug: 빌드 실패 해결 #22

Dockerfile, build.gradle, compose.yaml, src/main/java/com/househub/backend/common/config/RedisConfig.java, src/main/java/com/househub/backend/common/config/WebSecurityConfig.java, src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java, src/main/java/com/househub/backend/domain/agent/repository/AgentRepository.java, src/main/java/com/househub/backend/domain/auth/controller/AuthController.java, src/main/java/com/househub/backend/domain/auth/service/AuthService.java, src/main/java/com/househub/backend/domain/auth/service/EmailService.java, src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/househub/backend/domain/auth/service/impl/EmailServiceImpl.java
- 개인 메일을 이용하여 실제 이메일 발송 로직 추가
- 이미 가입된 계정에 대한 이메일인 경우에 대한 예외 처리 추가
- 배포 환경에서 빌드 과정에서 발생한 에러 해결
- 개인 메일을 이용하여 실제 이메일 발송 로직 추가
- 이미 가입된 계정에 대한 이메일인 경우에 대한 예외 처리 추가
- 배포 환경에서 빌드 과정에서 발생한 에러 해결
- #65
=> byungchan, feature: 실제 이메일 발송 로직 추가

src/main/java/com/househub/backend/domain/sms/dto/AligoHistoryResDto.java, src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java, src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java, src/main/java/com/househub/backend/domain/sms/entity/Sms.java, src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java, src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java
- aligo api로부터 정보를 갱신하는 dto와 내부 비즈니스 로직을 위한 dto를 분할
- 내부 비즈니스 로직 용 mvc 구현
- dto 명칭 변경
- dto 내부에 변환로직 구현
- #54
=> youngseok, feat: 알리고 api와 프론트 엔드의 dto 분할 #54

build.gradle, src/main/java/com/househub/backend/domain/auth/service/impl/EmailServiceImpl.java, src/main/java/com/househub/backend/domain/consultation/dto/ConsultationResDto.java
- ConsultationResDto builder에 id값이 빠져있어 추가함
위와 동일
- #25
=> siyoon, fix: 상담 기능 백엔드 버그 수정 #25

Dockerfile
- Dockerfile 파일 수정(jar 파일 실행 명령어 수정)
- Dockerfile 파일 수정(jar 파일 실행 명령어 수정)
- #80
=> Dockerfile 빌드 에러 해결

.github/workflows/deploy.yml
- deploy.yml 파일 수정(application.yml 파일 누락된 변수 추가)
- deploy.yml 파일 수정
- #84
=> byungchan, fix: Gihub Actions deploy.yml applciation.yml 파일 누락된 변수 추가

src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
- WebSecurityConfig 파일 수정
- WebSecurityConfig 파일 수정
- #87
=> 스웨거 접속 URL 에 대한 CORS 설정 허용

src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
- 프론트엔드 연동 시 CORS 에러 해결
- 프론트엔드 연동 시 CORS 에러 해결
- #87
=> fix: 프론트엔드 연동 시 CORS 에러 해결

src/main/java/com/househub/backend/common/dto/PaginationDto.java, src/main/java/com/househub/backend/domain/contract/controller/ContractController.java, src/main/java/com/househub/backend/domain/contract/dto/ContractListResDto.java, src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java, src/main/java/com/househub/backend/domain/contract/service/ContractService.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/househub/backend/domain/property/controller/PropertyController.java, src/main/java/com/househub/backend/domain/property/dto/PropertyListResDto.java, src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java, src/main/java/com/househub/backend/domain/property/service/PropertyService.java, src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java, src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java, src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
- 매물, 계약 조회 시 페이지네이션 dto 추가
- 검색 기능 변경
- 전체 매물, 계약 조회 시 응답 dto 구조 변경
- query 애너테이션에서 like -> = 으로 변경
- #13 
- #38
=> seongeun, feat: 매물, 계약 조회 시 페이지네이션 dto 추가

src/main/java/com/househub/backend/common/exception/BusinessException.java, src/main/java/com/househub/backend/common/exception/ErrorCode.java, src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java, src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/househub/backend/domain/auth/service/impl/EmailServiceImpl.java, src/main/java/com/househub/backend/domain/customer/entity/CustomerCandidate.java, src/main/java/com/househub/backend/domain/inquiry/controller/InquiryController.java, src/main/java/com/househub/backend/domain/inquiry/dto/InquiryDetailResDto.java, src/main/java/com/househub/backend/domain/inquiry/dto/InquiryListItemResDto.java, src/main/java/com/househub/backend/domain/inquiry/dto/InquiryListResDto.java, src/main/java/com/househub/backend/domain/inquiry/repository/InquiryRepository.java, src/main/java/com/househub/backend/domain/inquiry/service/InquiryService.java, src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
고객 문의 목록 및 상세정보 조회 API 구현
- 고객 문의 목록 및 상세정보 조회 API 구현
- #94
=> byungchan, feature: 고객 문의 목록 및 상세정보 조회 API 구현

src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java, src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java, src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java, src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
- 이 PR의 목적과 내용을 간략히 설명해주세요.
- 변경된 내용을 간략하게 나열해주세요.
- 
-
-
- 연관된 이슈가 있다면 연결해주세요. 예시: #103
=> youngseok, feat: 고객 전체조회 관련 로직 수정 #103

src/main/java/com/househub/backend/common/config/WebSecurityConfig.java, src/main/java/com/househub/backend/domain/contract/entity/Contract.java, src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java, src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java, src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java, src/main/java/com/househub/backend/domain/dashboard/dto/ChartDataResDto.java, src/main/java/com/househub/backend/domain/dashboard/dto/DashboardStatsResDto.java, src/main/java/com/househub/backend/domain/dashboard/dto/MultiDatasetChartResDto.java, src/main/java/com/househub/backend/domain/dashboard/dto/PropertyTypeCount.java, src/main/java/com/househub/backend/domain/dashboard/dto/RecentPropertyResDto.java, src/main/java/com/househub/backend/domain/dashboard/service/DashboardService.java, src/main/java/com/househub/backend/domain/dashboard/service/impl/DashboardServiceImpl.java, src/main/java/com/househub/backend/domain/property/enums/PropertyType.java, src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
- 대시보드에서 사용되는 통계 관련 데이터 API 구현
- 대시보드에서 사용되는 통계 관련 데이터 API 구현.
- 연관된 이슈가 있다면 연결해주세요. #101
=> byungchan, feature: 대시보드에서 사용되는 통계 관련 데이터 API 구현

src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java, src/main/java/com/househub/backend/domain/contract/entity/Contract.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
- Contract entity에 completedAt 추가
- #106
=> seongeun, feature: Contract entity에 completedAt 컬럼 추가 #106

src/main/java/com/househub/backend/common/config/WebSecurityConfig.java, src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java, src/main/java/com/househub/backend/domain/contract/entity/Contract.java, src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java, src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java, src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java, src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java, src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java, src/main/java/com/househub/backend/domain/dashboard/dto/ChartDataResDto.java, src/main/java/com/househub/backend/domain/dashboard/dto/DashboardStatsResDto.java, src/main/java/com/househub/backend/domain/dashboard/dto/MultiDatasetChartResDto.java, src/main/java/com/househub/backend/domain/dashboard/dto/PropertyTypeCount.java, src/main/java/com/househub/backend/domain/dashboard/dto/RecentPropertyResDto.java, src/main/java/com/househub/backend/domain/dashboard/service/DashboardService.java, src/main/java/com/househub/backend/domain/dashboard/service/impl/DashboardServiceImpl.java, src/main/java/com/househub/backend/domain/property/enums/PropertyType.java, src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java, src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
- 중간 발표 전 3차 배포
- 새로 개발된 API 및 기존 API 수정사항 반영
=> 중간 발표 전 3차 배포

src/main/java/com/househub/backend/domain/sms/controller/SmsController.java, src/main/java/com/househub/backend/domain/sms/dto/CreateUpdateTemplateReqDto.java, src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java, src/main/java/com/househub/backend/domain/sms/dto/SmsListResDto.java, src/main/java/com/househub/backend/domain/sms/dto/SmsTemplateListResDto.java, src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java, src/main/java/com/househub/backend/domain/sms/entity/Sms.java, src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java, src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java, src/main/java/com/househub/backend/domain/sms/repository/TemplateRepository.java, src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java, src/main/java/com/househub/backend/domain/sms/service/Impl/TemplateServiceImpl.java, src/main/java/com/househub/backend/domain/sms/service/SmsService.java, src/main/java/com/househub/backend/domain/sms/service/TemplateService.java
- 문자 목록 페이지, 문자 템플릿 목록 페이지, 문자 전송 페이지에서 사용되는 목록들에 pagination 적용
- keyword를 사용해 불필요한 요청용 dto 제거
- 문자 수신인 다중 선택 가능
- #54
=> youngseok, feat: 문자|문자 템플릿 페이지네이션 + 검색 관련 백엔드 수정사항 #54

src/main/java/com/househub/backend/common/exception/ErrorCode.java, src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/househub/backend/domain/consultation/dto/ConsultationResDto.java, src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java, src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryTemplateResDto.java, src/main/java/com/househub/backend/domain/inquiryTemplate/repository/InquiryTemplateSharedTokenRepository.java, src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateServiceImpl.java, src/test/java/com/househub/backend/domain/auth/service/AgentSignInServiceTest.java
- 상담 목록 조회 및 문의 템플릿 목록 조회 API 응답 데이터 추가
- 상담 목록 조회 및 문의 템플릿 목록 조회 API 응답 데이터 추가
- #114
=> 상담 목록 조회 및 문의 템플릿 목록 조회 API 응답 데이터 추가

src/main/java/com/househub/backend/HouseHubBackendApplication.java, src/main/java/com/househub/backend/common/config/WebSecurityConfig.java, src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java, src/main/java/com/househub/backend/domain/consultation/dto/ConsultationListResDto.java, src/main/java/com/househub/backend/domain/consultation/enums/ConsultationStatus.java, src/main/java/com/househub/backend/domain/consultation/repository/ConsultationRepository.java, src/main/java/com/househub/backend/domain/consultation/service/ConsultationService.java, src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java, src/test/java/com/househub/backend/domain/consultation/service/ConsultationServiceTest.java
- 상담 목록 조회 API 구현사항 배포 서버에 반영
- 상담 목록 조회 API 구현사항 배포 서버에 반영
- 연관된 이슈가 있다면 연결해주세요. #126
=> 상담 목록 조회 API 구현사항 배포 서버에 반영

src/main/java/com/househub/backend/common/config/WebSecurityConfig.java, src/main/java/com/househub/backend/domain/region/controller/RegionController.java, src/main/java/com/househub/backend/domain/region/dto/RegionOptionDto.java, src/main/java/com/househub/backend/domain/region/entity/Region.java, src/main/java/com/househub/backend/domain/region/repository/RegionRepository.java, src/main/java/com/househub/backend/domain/region/service/RegionCsvImportService.java, src/main/java/com/househub/backend/domain/region/service/RegionReadService.java
- .csv 파일 파싱해서 전국 지역 데이터 DB 업데이트 API 구현
- 전국 지역 데이터 기반 지역 목록 조회 API 구현
- .csv 파일 파싱해서 전국 지역 데이터 DB 업데이트 API 구현
- 전국 지역 데이터 기반 지역 목록 조회 API 구현
- 연관된 이슈가 있다면 연결해주세요. #144
=> 전국 지역 데이터 기반 지역 목록 조회 API 구현

src/main/java/com/househub/backend/domain/contract/dto/UpdateContractReqDto.java, src/main/java/com/househub/backend/domain/contract/entity/Contract.java, src/main/java/com/househub/backend/domain/contract/service/ContractStore.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractStoreImpl.java, src/main/java/com/househub/backend/domain/property/repository/PropertyRepositoryCustomImpl.java
- 계약 수정 안되는 부분 수정
- 매물 검색 동작 안되는 부분 수정
- ex) '제주특별자치도' -> '제주'만 입력해도 되도록
- #37 
- #151
=> seongeun, fix: contract update 수정 #37

src/main/java/com/househub/backend/domain/contract/dto/ContractSearchDto.java, src/main/java/com/househub/backend/domain/contract/dto/CreateContractReqDto.java, src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java, src/main/java/com/househub/backend/domain/contract/dto/UpdateContractReqDto.java, src/main/java/com/househub/backend/domain/contract/entity/Contract.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
- 삭제된 고객일 경우 해당 계약 수정 불가
- 계약 요청 dto 에 active 추가
- #133
=> seongeun, fix: 삭제된 고객일 경우 계약 수정 불가, 계약 요청 dto 에 active 추가 #133

src/main/java/com/househub/backend/domain/sms/service/impl/AligoServiceImpl.java
- 이 PR의 목적과 내용을 간략히 설명해주세요.
- 변경된 내용을 간략하게 나열해주세요.
- 
-
-
- 연관된 이슈가 있다면 연결해주세요. 예시: #12
=> youngseok, feat: 문자 테스트모드 해제 #121

src/main/java/com/househub/backend/domain/sms/service/impl/AligoServiceImpl.java
=> 문자 테스트 모드 해제 반영

src/main/java/com/househub/backend/domain/auth/dto/SignUpReqDto.java, src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java, src/main/java/com/househub/backend/domain/consultation/dto/ConsultationReqDto.java, src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
- 회원가입/로그인 및 신규 고객에 대한 상담 등록 버그 해결
- 커밋 참고
- 
- #178 
- #180
=> 회원가입/로그인 및 신규 고객에 대한 상담 등록 버그 해결

src/main/java/com/househub/backend/common/exception/ErrorCode.java, src/main/java/com/househub/backend/domain/contract/dto/ExpiringContractItemResDto.java, src/main/java/com/househub/backend/domain/contract/dto/ExpiringContractListResDto.java, src/main/java/com/househub/backend/domain/contract/enums/ContractType.java, src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java, src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java, src/main/java/com/househub/backend/domain/dashboard/service/DashboardService.java, src/main/java/com/househub/backend/domain/dashboard/service/impl/DashboardServiceImpl.java
월 별 만료 예정 계약 목록 조회 API 구현
- 월 별 만료 예정 계약 목록 조회 API 구현
- #189
=> 월 별 만료 예정 계약 목록 조회 API 구현

src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java
- 공개 매물 조회 버그 해결 
- 커밋 참고
- #209
=> byungchan, fix: 공개 매물 조회 버그 해결 #209

src/main/java/com/househub/backend/common/exception/ErrorCode.java, src/main/java/com/househub/backend/domain/auth/service/EmailVerificationService.java
- 이미 가입된 이메일의 경우 예외 처리 추가
- 커밋 참고
- #232
=> fix: 이미 가입된 이메일의 경우 예외 처리 추가 #232

src/main/java/com/househub/backend/common/exception/ErrorCode.java, src/main/java/com/househub/backend/domain/auth/service/EmailVerificationService.java
=> 최종 발표 전 6차 배포

src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java, src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
- 계약 상태 변경( 진행중 -> 완료 ) 오류 로직 수정
- #241
=> seongeun, fix: 계약 상태 수정 버그 해결

src/main/java/com/househub/backend/common/config/AsyncConfig.java, src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java, src/main/java/com/househub/backend/domain/notification/controller/NotificationController.java, src/main/java/com/househub/backend/domain/notification/event/InquiryCreatedEvent.java, src/main/java/com/househub/backend/domain/notification/event/InquiryEmailListener.java, src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationListener.java, src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationReadyEvent.java, src/main/java/com/househub/backend/domain/notification/event/InquirySseListener.java, src/main/java/com/househub/backend/domain/notification/repository/NotificationRepository.java, src/main/java/com/househub/backend/domain/notification/service/EmailService.java, src/main/java/com/househub/backend/domain/notification/service/NotificationReader.java, src/main/java/com/househub/backend/domain/notification/service/NotificationService.java, src/main/java/com/househub/backend/domain/notification/service/SseEmitterService.java, src/main/java/com/househub/backend/domain/notification/service/impl/NewInquiryCreatedContentProvider.java, src/main/java/com/househub/backend/domain/notification/service/impl/NotificationReaderImpl.java
- 문의 생성 후 알림 전송 구조 개선 (AFTER_COMMIT & 이벤트 리스너 분리)
- 커밋 참고
- #239
=> 문의 생성 후 알림 전송 구조 개선 (AFTER_COMMIT & 이벤트 리스너 분리) #239

src/main/java/com/househub/backend/common/config/AsyncConfig.java, src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java, src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java, src/main/java/com/househub/backend/domain/notification/controller/NotificationController.java, src/main/java/com/househub/backend/domain/notification/event/InquiryCreatedEvent.java, src/main/java/com/househub/backend/domain/notification/event/InquiryEmailListener.java, src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationListener.java, src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationReadyEvent.java, src/main/java/com/househub/backend/domain/notification/event/InquirySseListener.java, src/main/java/com/househub/backend/domain/notification/repository/NotificationRepository.java, src/main/java/com/househub/backend/domain/notification/service/EmailService.java, src/main/java/com/househub/backend/domain/notification/service/NotificationReader.java, src/main/java/com/househub/backend/domain/notification/service/NotificationService.java, src/main/java/com/househub/backend/domain/notification/service/SseEmitterService.java, src/main/java/com/househub/backend/domain/notification/service/impl/NewInquiryCreatedContentProvider.java, src/main/java/com/househub/backend/domain/notification/service/impl/NotificationReaderImpl.java
=> 최종 발표 전 8차 배포

src/main/java/com/househub/backend/domain/crawlingProperty/controller/CrawlingPropertyController.java, src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyReqDto.java, src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyTagResDto.java, src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryCustom.java, src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java, src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
=> 최종 발표 전 9차 배포
